# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 朱求志的博客
email: zhuqiuzhi91 at gmail.com
description: > # this means to ignore newlines until "baseurl:"
  朱求志的博客－记录自己学习计算机科学的所思所得和工作过程中的学到的知识。
baseurl: "" # the subpath of your site, e.g. /blog
url: "zhuqiuzhi.github.io" # the base hostname & protocol for your site
github_username:  zhuqiuzhi

# Build settings
markdown: kramdown
