# Site settings
title: 朱求志的博客
email: zhuqiuzhi91 at gmail.com
description: > # this means to ignore newlines until "baseurl:"
  记录自己学习计算机科学的所思所得和工作过程中的学到的知识。
baseurl: "/"
url: "zhuqiuzhi.github.io" # the base hostname & protocol for your site
github_username:  zhuqiuzhi

# Build settings
markdown: kramdown

# Dependencies
markdown:         redcarpet
#highlighter:      pygments
highlighter:     rouge 

# Gems
plugins: [jekyll-paginate]
paginate:         5

# About/contact
author:
  name:              朱求志
  url:               https://github.com/zhuqiuzhi
  email:             zhuqiuzhi91@gmail.com 

github: https://github.com/zhuqiuzhi
