# Site settings
title: 朱求志
email: zhuqiuzhi91 at gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Algorithms + Data Structures = Programs
url: "https://zhuqiuzhi.github.io" # the base hostname & protocol for your site
github_username:  zhuqiuzhi
baseurl:

# Build settings
markdown: kramdown

# Dependencies
highlighter:     rouge 

# Gems
plugins: [jekyll-paginate]
paginate:         5

github: https://github.com/zhuqiuzhi
